package com.haw.srs.customerservice.enums;

public enum Category {
    BARBELL, DUMBBELL, MASCHINE, KABELTURM, BESCHWERTES_KOERPERGEWICHT, UNTERSTUETZER_KOERPER, NUR_WIEDERHOLUNGEN, CARDIO_TRAINING_DAUER
}
